(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
// Generated by CoffeeScript 1.10.0
(function() {
  var account, etag, fetchRepos, minixhr, repos, request, showRepos;

  minixhr = require('minixhr');

  repos = '';

  etag = localStorage.getItem('etag');

  account = 'pepebecker';

  request = {
    url: "https://api.github.com/users/" + account + "/repos",
    method: 'HEAD'
  };

  minixhr(request, function(data, response, xhr, header) {
    if (etag !== header.Etag || localStorage.getItem('repos').length === 0) {
      localStorage.setItem('etag', header.Etag);
      return fetchRepos();
    } else {
      repos = JSON.parse(localStorage.getItem('repos'));
      return showRepos();
    }
  });

  fetchRepos = function() {
    return minixhr("https://api.github.com/users/" + account + "/repos", function(data, response, xhr, header) {
      localStorage.setItem('repos', data, null, 4);
      repos = JSON.parse(data);
      return showRepos();
    });
  };

  showRepos = function() {
    var content, description, i, j, name, ref, url;
    content = '';
    content = content + '<p>My GitHub Reposetories</p>\n';
    for (i = j = 0, ref = repos.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      name = repos[i].name;
      url = repos[i].html_url;
      description = 'no description available';
      if (repos[i].description !== null) {
        if (repos[i].description.length > 0) {
          description = repos[i].description;
        } else {
          description = 'no description available';
        }
      }
      if (repos[i].name === (account + ".github.io")) {
        description = 'This repo contains the source of this site';
      }
      content += "<li class='repo'><a href='" + url + "'>" + name + "</a><p class='discription'>" + description + "</p></li>\n";
    }
    return document.getElementById("repos").innerHTML = content;
  };

}).call(this);

},{"minixhr":2}],2:[function(require,module,exports){
var XMLHttpRequest  = require('xhrpolyfill')
module.exports = function xhr2 (params, callback) {
  var url = typeof params === 'string' ? params : params.url
  var method = params.method || (params.data ? 'POST': 'GET')
  var body = params.data
  var H = params.headers ? params.headers : params.body ? {
    'X-Requested-With' :'XMLHttpRequest',
    'Content-Type'     :'application/x-www-form-urlencoded'
  } : {}
  var xhr = XMLHttpRequest()
  if (!xhr) throw new Error('No AJAX support')
  xhr.open(method, url)
  for (var key in H) xhr.setRequestHeader(key, H[key])
  xhr.onload = xhr.onerror = function (response) {
    var Hjson = {}, h = xhr.getAllResponseHeaders()
    ;(h.match(/([^\n\r:]+):([^\n\r]+)/g)||[]).forEach(function(item){
      var tmp = item.split(': ')
      Hjson[tmp[0]] = tmp[1]
    })
    if (callback) callback(this.response, response, xhr, Hjson)
  }
  xhr.send(body||null)
}

},{"xhrpolyfill":3}],3:[function(require,module,exports){
var xhrFactory = (function getXHRfactory (factories) {
  for (var i=0, xhr, X, len=factories.length; i<len; i++) {
    try { X = factories[i]; xhr = X();
      return window.XMLHttpRequest ? X : window.XMLHttpRequest = X;
    } catch (e) { continue; }
  }
})([
  function () {return new XMLHttpRequest();},// IE10+,FF,Chrome,Opera,Safari
  function () {return new ActiveXObject("Msxml3.");},            // IE9
  function () {return new ActiveXObject("Msxml2.XMLHTTP.6.0");}, // IE8
  function () {return new ActiveXObject("Msxml2.XMLHTTP.3.0");}, // IE7
  function () {return new ActiveXObject("Msxml2.XMLHTTP");},     // IE6
  function () {return new ActiveXObject("Microsoft.XMLHTTP");},  // IE5
  function () {return null;}
]);
module.exports = function getXHR() { return xhrFactory(); }

},{}]},{},[1]);
